# Generated by Django 5.2.8 on 2025-11-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreOffers',
            fields=[
                ('offer_id', models.TextField(primary_key=True, serialize=False)),
                ('vendor', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('product_name_clean', models.TextField(blank=True, null=True)),
                ('vendor_subcategory_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_offers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorePrices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('field_synthetic_field', models.TextField(blank=True, db_column='__synthetic__', null=True)),
                ('offer_id', models.TextField(blank=True, null=True)),
                ('price_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_prices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimVendorCategory',
            fields=[
                ('vendor_category_id', models.TextField(primary_key=True, serialize=False)),
                ('vendor', models.TextField(blank=True, null=True)),
                ('vendor_category_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_vendor_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimVendorSubcategory',
            fields=[
                ('vendor_subcategory_id', models.TextField(primary_key=True, serialize=False)),
                ('vendor_category_id', models.TextField(blank=True, null=True)),
                ('vendor', models.TextField(blank=True, null=True)),
                ('vendor_category_name', models.TextField(blank=True, null=True)),
                ('vendor_subcategory_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_vendor_subcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VLastestOfferPrices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_id', models.TextField(blank=True, null=True)),
                ('price_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v_lastest_offer_prices',
                'managed': False,
            },
        ),
    ]
