version: 2
models:
  - name: core_prices
    columns:
      - name: offer_id
        data_tests:
          - not_null
      - name: price_value
        data_tests:
          - not_null
  - name: core_offers
  - name: dim_vendor_category
  - name: dim_vendor_subcategory
  - name: core_products_listings
  - name: dim_brand
    columns:
      - name: vendor_brand_id
        data_tests:
          - not_null
      - name: vendor_brand_name
        data_tests:
          - not_null
